name: Build and Deploy to itch.io

on:
  push:
    branches: [ main ]  # Trigger on push to main branch
  workflow_dispatch:    # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Zip Repository
      run: zip -r game.zip . -x '*.git*'
      
    - name: Download Butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler -V
    
    - name: Deploy to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        ./butler push game.zip hieuimba/guess-the-elo:html5
        
    - name: Cleanup
      run: rm game.zip butler butler.zip
